### ISSUE TITLE
Function Parameter Lists are Parsed in Reverse

### ISSUE THREAD

**Issue by Mercerenies** [melvic-ybanez/dry#23]
Hi there! I love what you've got here; this language has beautiful syntax.

I was trying out Dry earlier today, and it looks like your parser may be parsing function parameter lists backwards.

```
def foo(a, b) {
    println(a);
    println(b);
}

foo(1, 2);
```

I would expect this snippet to print 1 and then 2, but it actually prints 2 first and then 1, suggesting that `a` is getting bound to 2 and `b` to 1.

**Comment by melvic-ybanez** [comment]
Thanks for the report @Mercerenies
